Fix TS errors in AttributeOverview
miles-no/booster2022-gather-your-party-with-svelte pull request #36
Opened 2022-03-09 19:17 UTC by boyum

I fucked up and commited the Markdown files early which are part of #35, SORRY

2022-03-09 20:05 UTC, dagerikhl approved these changes
Again, thanks @boyum , great work! :D

2022-03-10 06:50 UTC, palexcast requested changes
Contains some code that won't compile

2022-03-10 06:50 UTC, palexcast commented on src/lib/components/attributes/attribute-overview/AttributeOverview.svelte
> +	};
This contains some of the solution code, but these two values are not set further up here.

```suggestion
	};
```

2022-03-10 07:14 UTC, palexcast approved these changes
💚

2022-03-10 07:14 UTC, merged